// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qvzoqglsnfqnifwlqblb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF2em9xZ2xzbmZxbmlmd2xxYmxiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc1ODY0MTUsImV4cCI6MjA3MzE2MjQxNX0.HcNaWC044mi3cZV-Hxk7JxaLM0FzN4lxq89FbPfDTfM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});